### PR TITLE
Fix vp8 keyframe detection

### LINKED ISSUE #234: Detection of VP8 keyframe
It happens that the code for detecting a keyframe for VP8 packets is a little bit wrong, instead of accessing parsed packet's payload the original payload was taken into account instead. Tested out with a custom code for extracting the keyframes and the new line works as expected.

```elixir
defmodule ExWebRTC.RTP.VP8 do
  @moduledoc """
  Utilities for RTP packets carrying VP8 encoded payload.
  """

  alias ExRTP.Packet
  alias ExWebRTC.RTP.VP8

  @doc """
  Checks whether RTP payload contains VP8 keyframe.
  """
  @spec keyframe?(Packet.t()) :: boolean()
  def keyframe?(%Packet{payload: rtp_payload}) do
    # RTP payload contains VP8 keyframe when P bit in VP8 payload header is set to 0
    # besides this S bit (start of VP8 partition) and PID (partition index)
    # have to be 1 and 0 respectively
    # for more information refer to RFC 7741 Sections 4.2 and 4.3

    with {:ok, vp8_payload} <- VP8.Payload.parse(rtp_payload),
      # ORIGINAL IMPLEMENTATION: <<_size0::3, _h::1, _ver::3, p::1, _size1::8, _size2::8, _rest::binary>> <- rtp_payload do
         <<_size0::3, _h::1, _ver::3, p::1, _size1::8, _size2::8, _rest::binary>> <- vp8_payload.payload do
      vp8_payload.s == 1 and vp8_payload.pid == 0 and p == 0
    else
      _err -> false
    end
  end
end

```

### PR DESCRIPTION
**Pull request by Karolk99**
Closes #234

### CODE REVIEW

File: test/ex_webrtc/rtp/vp8_test.exs [hunk 1]
```diff
@@ -0,0 +1,35 @@
...
+      <<0x80, 0x6F, 0x61, 0x8F, 0xD5, 0x36, 0xDC, 0x15, 0x1B, 0x4A, 0xB5, 0x29, 0x78, 0x9, 0xA1,
+        0x93, 0xA0, 0x5B, 0xD8, 0xF1, 0xDE, 0x87, 0x23, 0x5A, 0xB9, 0x19, 0x97, 0xB7, 0xBD, 0xBF,
+        0xF7, 0x6E, 0xAD, 0x82, 0xC4, 0x70, 0x1C, 0xC9, 0x3A, 0xB4, 0x1F, 0x13, 0x45, 0xB5, 0xF1,
+        0x0, 0xA5, 0xA5, 0xA9, 0xD0, 0xA5, 0xDF, 0x67, 0x88, 0x26, 0x30, 0x32>>
+
+    {:ok, packet2} = Packet.decode(binary2)
+    assert not VP8.keyframe?(packet2)
+
+    # https://github.com/elixir-webrtc/ex_webrtc/issues/234
+    {:ok, binary_packet3} = File.read(@vp8_packet)
```
Comment (roznawsk) [inline test/ex_webrtc/rtp/vp8_test.exs]: Nitpick: 
```suggestion
    binary_packet3 = File.read!(@vp8_packet)
```

**Review by roznawsk — APPROVED** [review]
